-- CREATE TABLE Photos (
--     id SERIAL PRIMARY KEY,
--     letter VARCHAR(1),
--     letterCount INTEGER,
--     photoUrl VARCHAR
-- );

-- CREATE TABLE Users (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR,
--     email VARCHAR,
--     hash VARCHAR,
--     address VARCHAR,
--     city VARCHAR,
--     state VARCHAR(2),
--     zip INTEGER
-- );

-- CREATE TABLE Orders (
--     id SERIAL PRIMARY KEY,
--     userID INTEGER REFERENCES Users,
--     photoIDs VARCHAR[],
--     date DATE,
--     price DECIMAL,
--     processed BOOLEAN,
--     paid BOOLEAN,
--     shipped BOOLEAN,
--     delivered BOOLEAN
-- );